name: Run Python and Capture Output

on:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        
      - name: Run Python script and capture output
        id: run_script
        run: |
          output=$(python3 ./scripts/python_script.py)
          echo "script_output=${output}" >> $GITHUB_OUTPUT

      - name: Use output from previous step
        run: |
          
          echo "The Python script returned: ${{ steps.run_script.outputs.script_output }}"
      

      - name: convert json array to bash array
          
        run: |
          TARGET=${{ steps.run_script.outputs.script_output }}
          BASH_ARRAY=($(echo "$TARGET" | jq -r '.[]'))
          
                    if [[ -n "$TARGET" ]]; then
              echo "Bash array elements:"
              for item in "${BASH_ARRAY[@]}"; do
                  echo "Item: $item"
              done
          else
              echo "No data in TARGET"
          fi
          
